// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwr8Xn0gAy9KALtvwgGURORAUUK2yemIg',
    appId: '1:212948976248:web:604f426c59586d3b92638d',
    messagingSenderId: '212948976248',
    projectId: 'clusternest-8dae7',
    authDomain: 'clusternest-8dae7.firebaseapp.com',
    storageBucket: 'clusternest-8dae7.firebasestorage.app',
    measurementId: 'G-XPB52VHFWY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwhA4LG69UkyJXNDuSXqD0IH02zyDAB4o',
    appId: '1:212948976248:android:1fef3a1aba724d6a92638d',
    messagingSenderId: '212948976248',
    projectId: 'clusternest-8dae7',
    storageBucket: 'clusternest-8dae7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCaFi7hRknr0fB5kaYzMVvtIJhla4KGF4o',
    appId: '1:212948976248:ios:6a8557476396f2b192638d',
    messagingSenderId: '212948976248',
    projectId: 'clusternest-8dae7',
    storageBucket: 'clusternest-8dae7.firebasestorage.app',
    iosBundleId: 'com.example.clusternest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCaFi7hRknr0fB5kaYzMVvtIJhla4KGF4o',
    appId: '1:212948976248:ios:6a8557476396f2b192638d',
    messagingSenderId: '212948976248',
    projectId: 'clusternest-8dae7',
    storageBucket: 'clusternest-8dae7.firebasestorage.app',
    iosBundleId: 'com.example.clusternest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAwr8Xn0gAy9KALtvwgGURORAUUK2yemIg',
    appId: '1:212948976248:web:5ec7d79f04e0caa592638d',
    messagingSenderId: '212948976248',
    projectId: 'clusternest-8dae7',
    authDomain: 'clusternest-8dae7.firebaseapp.com',
    storageBucket: 'clusternest-8dae7.firebasestorage.app',
    measurementId: 'G-BRW3QR3H49',
  );
}
